/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [{
    _id: "rgaTLrZGlk0",
    title: "Learn music theory in half an hour.",
    profile: "https://yt3.ggpht.com/Fy04H8gLPQY-cnX3g5EUOILZ1NxktAJ2c5si0dpWbA79TMWExQUCOwO_lbA_hytDQgg-lgxc=s48-c-k-c0x00ffffff-no-rj",
    creator: "ANDREW HUANG",
    description: "If you're new here, my name is Andrew Huang and I'm a musician who works with many genres and many instruments - and I've also made music with many things that aren't instruments like balloons, pants, water, and dentist equipment.",
    category: "Music Theory",
  },
  {
    _id: "8aRx4HMLY5Q",
    title: "Free Music Production and Recording Software - Best Free DAWs",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu-uiFoWQB45mQHgwp6FAy72fMQv8UyytSdVRCL6gA=s48-c-k-c0x00ffffff-no-rj",
    creator: "In The Mix",
    description: "In this video, I show you the best free DAWs. These free audio editing softwares allow you to record, edit and mix music at no cost. Whether you are looking for a free beatmaking app, a way to record a microphone in high quality or simply want to try a new free music production software, these might be a great fit for you. ",
    category: "Music Production",
  },
  {
    _id: "-X84GG06g-c",
    title: "Beginner Guitar Lesson Starter Pack",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu_UNIoRoOg-w9ab1Ba8cbugwRP6NakDY_5V5tX7JA=s48-c-k-c0x00ffffff-no-rj",
    creator: "Redlight Blue",
    description: "Beginner guitarists learning online have an overwhelming number of lessons and courses to choose from. Luckily, you only need this one. Soon enough, you’ll be playing your first song.",
    category: "Guitar Lessons",
  },
  {
    _id: "awjmFyHiecM",
    title: "How To Record & Mix Vocals Like A Pro (Start To Finish)",
    profile: "https://yt3.ggpht.com/mWGUK0c8zAVwT8E5fdDBbPJi7yz78pfM7BkEvWn1HajOH30iA3Yo62yZEcoskRFA2uWdK_2Z=s48-c-k-c0x00ffffff-no-nd-rj",
    creator: "Aden Foyer",
    description: "How to record and mix vocals yourself like a pro start to finish! Substitute teacher Paul Hers is a producer, singer and songwriter who´s sang on 1# Hits and worked with top names like Martin Garrix, Alan Walker, ASAP Rocky.",
    category: "Vocal Traning",
  },
  {
    _id: "rVlFh3hDF2U",
    title: "7 Techniques Piano Beginners Don't Spend Enough Time On",
    profile: "https://yt3.ggpht.com/WLgQacDL-zqLs6McwQmeaumTCGTgU7cmzYzVI8Gjk7xNqEXGdE5E5R6XZC-xgb33WuqwCFAt=s48-c-k-c0x00ffffff-no-rj",
    creator: "Learn Piano with Jazer Lee",
    description: "Have you just started learning how to play the piano or have come back to it after many years of not playing or practising? This video lesson tutorial outlines a checklist every beginner (and even intermediate) piano player should take note. There are 7 techniques listed and watch until the end for a very cute footnote.",
    category: "Piano Lessons",
  },
  {
    _id: "l4v3UKq-dU4",
    title: "5 Amateur Music Production Mistakes (and how to fix them) 💀",
    profile: "https://yt3.ggpht.com/Qj1XYzhs850OfPefGUt_P5ejABsbpWS-lfCtmZeRDAY8hIcDdNsyKV0HAv9UFgy3lvuLo29Zzw=s48-c-k-c0x00ffffff-no-rj",
    creator: "Nathan James Larsen",
    description: "81% of new music producers make these 5 deadly production mistakes.. This video will show you what they are and how to fix them 🟠",
    category: "Music Production",
  },
  {
    _id: "De97zQi5rzc",
    title: "Music Theory Masterclass 1: Drilling the Basics",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu8KftEzNntkwmtjJE9y3wiHL1C3XUNesDGT0epfMw=s48-c-k-c0x00ffffff-no-rj",
    creator: "Rick Beato",
    description: "In this first Music Theory Masterclass we will drill the basics of music theory.",
    category: "Music Theory",
  },
  {
    _id: "_eKTOMhpy2w",
    title: "Music Theory in 16 Minutes",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu-DpUbjB4HEzdvBUhcGNYKbSRJnPPK-iaypLXWlvw=s48-c-k-c0x00ffffff-no-rj",
    creator: "Guy Michelmore",
    description: "Hi everyone – just want to let you know about our course, Learn Music Theory. It's quick, practical and fun, and takes you from square one through to more advanced topics like modes and chromatic harmony.",
    category: "Music Theory",
  },
  {
    _id: "EME7dAaGr60",
    title: "3 GUITAR 🎸 Exercises YOU CANNOT MISS!! 😱",
    profile: "https://yt3.ggpht.com/OtYd2GPoqvnxzRbfWWnBhBuubKBwcqv91fcbFuiJBurUShSsrU3qIvpSkQSlrScVmDWBAVIINg=s48-c-k-c0x00ffffff-no-rj",
    creator: "FrontRow Guitar",
    description: " Seekhiye Guitar aur Baniye YouTube ke Biggest Star",
    category: "Guitar Lessons",
  },
  {
    _id: "2pirdPK5avU",
    title: "How I'd Learn Music Theory (If I Had To Start Over)",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu8MfdX04t17UipPf0AsXU75VG7-4Djc7rmJmcNt=s48-c-k-c0x00ffffff-no-rj",
    creator: "12tone",
    description: "If I could start again, a million miles away...",
    category: "Music Theory",
  },
  {
    _id: "rTMN8rCBWkw",
    title: "(Part1) 11 Basic Guitar Chords that every Beginner Guitarist should know",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu_R2u6TJMrsvJiLF4jhs9qIky1GgPF5ytiY_UPdUA=s48-c-k-c0x00ffffff-no-rj",
    creator: "Piku Attri",
    description: "hello everyone! it's piku and welcome back to my channel, today we'll be learning the very basic and essential lesson for beginner guitarist. In this lesson we're going to learn all basic/open chords that you must know as a guitarist in a very simple and easy way! So, grab your guitar and let's get started.",
    category: "Guitar Lessons",
  },
  {
    _id: "BBz-Jyr23M4",
    title: "Guitar Lesson 1 - Absolute Beginner? Start Here! [Free 10 Day Starter Course]",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu-U5nkV9yjWn3IHBgVlCeC8yGc4kxVKBXhYZAPAdUs=s48-c-k-c0x00ffffff-no-rj",
    creator: "Andy Guitar",
    description: "Hi I'm Andy Crowley, and welcome to this 10 day guitar starter course! Playing guitar as close to everyday as possible is the BEST WAY TO IMPROVE in the shortest amount of time - especially for total beginners!",
    category: "Guitar Lessons",
  },
  {
    _id: "AXnVp2zLTYY",
    title: "How to get started making music",
    profile: "https://yt3.ggpht.com/Fy04H8gLPQY-cnX3g5EUOILZ1NxktAJ2c5si0dpWbA79TMWExQUCOwO_lbA_hytDQgg-lgxc=s48-c-k-c0x00ffffff-no-rj",
    creator: "ANDREW HUANG",
    description: "If you're new here, my name is Andrew Huang and I'm a musician who works with many genres and many instruments - and I've also made music with many things that aren't instruments like balloons, pants, water, and dentist equipment.",
    category: "Music Production",
  },
  {
    _id: "mYVFF-MTkOM",
    title: "PRODUCING Music For BEGINNERS - How To START Making MUSIC (Software, Hardware, Mindsets)",
    profile: "https://yt3.ggpht.com/1cetL9-lz1_ZIo6UliW5Hr_RgXhbptCzffRnTSNPnUO9WArJHDt8KPyzjnsRmpdH1LQWev4Yjw=s48-c-k-c0x00ffffff-no-rj",
    creator: "Sound Constraints",
    description: "In this video, I go over HOW you can start PRODUCING MUSIC for Beginners quickly, easily, and CHEAPLY.  I cover how to start making music by breaking down the Software, Hardware, and the Mindsets that you need to start producing the music you love(:",
    category: "Music Production",
  },
  {
    _id: "FgFXlGjIbyk",
    title: "Music Production & Beat Making Process EXPLAINED",
    profile: "https://yt3.ggpht.com/hAt-w6dYC791yR7O5HH3NK-b9WdOwyubINkZNNCeST1QWVR8XJgUut7TQDMZtJyEN_pOlJ4b=s48-c-k-c0x00ffffff-no-nd-rj",
    creator: "TAETRO",
    description: "A fully narrated music production process video to show you my general beat making process. For more music, live sessions and tutorials.",
    category: "Music Production",
  },
  {
    _id: "06pyLmYs-1g",
    title: "How To Memorize Every Major & Minor Chord On Piano",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu8HK6VkHq3J8ANxIdpMzjTaNyzP3LQ38XrGnrcc=s48-c-k-c0x00ffffff-no-rj",
    creator: "Piano From Scratch",
    description: "As a reminder - The outside 5th is the same for both Major & Minor. Major Middle note (Major 3rd) is 2 Whole Steps From the Root. Minor Middle note (Minor 3rd) is 1 1/2 whole steps from the Root",
    category: "Piano Lessons",
  },
  {
    _id: "bzNKQ2FkEJI",
    title: "7 Days To Learning Piano (Beginner Lesson)",
    profile: "https://yt3.ggpht.com/RjzIRqzx57PesN0mx1RErfqZQrQd1i7OgKBf3FKLiN_P23ki5zPJvsAn0TLcu_HFBsJL1qEDqQ=s48-c-k-c0x00ffffff-no-rj",
    creator: "Pianote",
    description: "Stay motivated with direct access to real teachers! Get personal support from our in-house team of teachers through personal feedback, live lessons, and Q&A sessions PLUS get access to NEW guest coaches where you’ll connect with world-class pianists and gain their best insights.",
    category: "Piano Lessons",
  },
  {
    _id: "suicntLcnko",
    title: "Week 1: Introduction to 'Sur' | Chandrani's Online Music Class",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu82vMNKHLiq4FLacpDGDtjPFzERbAggSIfGkhZGeQ=s48-c-k-c0x00ffffff-no-rj",
    creator: "Chandrani Sarma",
    description: "I wanted to start these online classes for those who have limited access to knowledge and tools of how to go about learning Classical music. Because I feel basic knowledge of Sur and Taal as well as musical terms like Scales or Saptak are important for any music lover who aspires to improve his/her singing projection. These classes will be uploaded every week, on Saturday, for 12 weeks.",
    category: "Vocal Traning",
  },
  {
    _id: "a_kVafB-0C4",
    title: "How to start playing piano or keyboard - basic technique and exercises",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu8HK6VkHq3J8ANxIdpMzjTaNyzP3LQ38XrGnrcc=s48-c-k-c0x00ffffff-no-rj",
    creator: "Piano From Scratch",
    description: "This video covers BASIC TECHNIQUE // 5 NOTE FINGER WORK // SIMPLE WHITE KEY IMPROV // STARTING TO PLAY CHORDS // BLACK KEY IMPROV",
    category: "Piano Lessons",
  },
  {
    _id: "VXD0p_g_UTg",
    title: "Play with 2 Hands on Piano (Practice these 10 Easy Exercises)",
    profile: "https://yt3.ggpht.com/WLgQacDL-zqLs6McwQmeaumTCGTgU7cmzYzVI8Gjk7xNqEXGdE5E5R6XZC-xgb33WuqwCFAt=s48-c-k-c0x00ffffff-no-rj",
    creator: "Learn Piano with Jazer Lee",
    description: "How to play with 2 Hands on Piano - Practice these Coordination Exercises.  A piano tutorial on piano hand independence, finger independence and hand coordination.",
    category: "Piano Lessons",
  },
  {
    _id: "QOBmBH6GVBg",
    title: "Voice Lessons for Beginners [Vocal Exercises Included]",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu9P-cYuO70WqcjHbLXjMKFOyomrMbZEDAnDskqgOQ=s48-c-k-c0x00ffffff-no-rj",
    creator: "SuperiorSinging",
    description: "I'm so excited you're here! Think of this channel as your perfect place to begin improving your singing voice no matter where you are in your vocal journey. I'm here to help you reach all your singing goals and dreams!",
    category: "Vocal Traning",
  },
  {
    _id: "_7UjHiETiq8",
    title: "Singing Classes | Basics of Singing | Class 1 | Lakshmi Madhusudan",
    profile: "https://yt3.ggpht.com/1hNMMTWM6IrLNtR-Pran0oK7YBIuikPI0tEbPv01bpfFxL8LjOYoLboDfluq6bVrI5qHwIfV=s48-c-k-c0x00ffffff-no-rj",
    creator: "LMS Academy",
    description: "SUBSCRIBE NOW, Love, Lakshmi Madhusudan",
    category: "Vocal Traning",
  },
  {
    _id: "omP375ELoYE",
    title: "Do You Sing GOOD or BAD?",
    profile: "https://yt3.ggpht.com/32aBDdmtasoVCCXxtYeHpaqSAMq-kTffsgLL5EA1aZnAZP_BrEeBtxee-hNCmNb28z7UtvvVDao=s48-c-k-c0x00ffffff-no-rj",
    creator: "AmaZane Channel",
    description: "Do you sing good or bad??? can everyone sing good? can everyone learn how to sing well?",
    category: "Vocal Traning",
  },
  {
    _id: "n2z02J4fJwg",
    title: "A Beginner's Guide to Music Theory",
    profile: "https://yt3.ggpht.com/ytc/AMLnZu8S8qLp2prK4K28qic5LTE-GtX5FUUzqm_nWtvBDg=s48-c-k-c0x00ffffff-no-rj-mo",
    creator: "InspirAspir",
    description: "Music Theory can be intimidating to learn as a beginner with no prior knowledge, however, it can improve your music writing skills significantly! As someone who never received a formal education on music theory, I'm here to teach what I believe to be the most important concepts a beginner should learn. I strongly believe in the concept of learning from your peers, so just remember I was once in your shoes!",
    category: "Music Theory",
  },

];